# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-02 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, verbose_name='类型')),
                ('value', models.CharField(max_length=10, verbose_name='码值')),
                ('words', models.CharField(max_length=50, verbose_name='文字')),
            ],
            options={
                'db_table': 'code',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missionstate', models.CharField(max_length=4, verbose_name='任务状态')),
                ('logerid', models.IntegerField(verbose_name='操作人')),
                ('logdate', models.DateTimeField(auto_now_add=True, verbose_name='日志记录时间')),
            ],
            options={
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missionname', models.CharField(max_length=100, verbose_name='任务名称')),
                ('missiontype', models.CharField(max_length=1, verbose_name='任务类别')),
                ('missionstate', models.CharField(max_length=4, verbose_name='任务状态')),
                ('usercompany', models.CharField(max_length=50, verbose_name='需求提交公司')),
                ('username', models.CharField(max_length=50, verbose_name='需求提交用户')),
                ('usertel', models.CharField(max_length=20, verbose_name='用户电话')),
                ('receivetime', models.DateField(auto_now_add=True, verbose_name='接收需求时间')),
                ('missionlevel', models.CharField(max_length=1, verbose_name='需求等级')),
                ('remark', models.CharField(max_length=1000, null=True, verbose_name='备注')),
                ('usertestdate', models.DateField(null=True, verbose_name='用户测试日期')),
                ('phdate', models.DateField(null=True, verbose_name='上线归档日期')),
            ],
            options={
                'db_table': 'mission',
            },
        ),
        migrations.AddField(
            model_name='log',
            name='missionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demand.Mission'),
        ),
    ]
