# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-02 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0002_auto_20191202_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
                ('filename', models.CharField(max_length=100, verbose_name='文件名称')),
                ('uploader', models.IntegerField(verbose_name='上传人')),
                ('uploaddate', models.DateField(auto_now_add=True, verbose_name='上传时间')),
                ('missionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demand.Mission')),
            ],
            options={
                'db_table': 'file',
            },
        ),
    ]
